// Code generated by protoc-gen-go. DO NOT EDIT.
// source: emoji.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmojizeRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmojizeRequest) Reset()         { *m = EmojizeRequest{} }
func (m *EmojizeRequest) String() string { return proto.CompactTextString(m) }
func (*EmojizeRequest) ProtoMessage()    {}
func (*EmojizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_emoji_f423687afb3d35a1, []int{0}
}
func (m *EmojizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmojizeRequest.Unmarshal(m, b)
}
func (m *EmojizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmojizeRequest.Marshal(b, m, deterministic)
}
func (dst *EmojizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmojizeRequest.Merge(dst, src)
}
func (m *EmojizeRequest) XXX_Size() int {
	return xxx_messageInfo_EmojizeRequest.Size(m)
}
func (m *EmojizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmojizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmojizeRequest proto.InternalMessageInfo

func (m *EmojizeRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type EmojizeReply struct {
	EmojizedText         string   `protobuf:"bytes,1,opt,name=emojized_text,json=emojizedText,proto3" json:"emojized_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmojizeReply) Reset()         { *m = EmojizeReply{} }
func (m *EmojizeReply) String() string { return proto.CompactTextString(m) }
func (*EmojizeReply) ProtoMessage()    {}
func (*EmojizeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_emoji_f423687afb3d35a1, []int{1}
}
func (m *EmojizeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmojizeReply.Unmarshal(m, b)
}
func (m *EmojizeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmojizeReply.Marshal(b, m, deterministic)
}
func (dst *EmojizeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmojizeReply.Merge(dst, src)
}
func (m *EmojizeReply) XXX_Size() int {
	return xxx_messageInfo_EmojizeReply.Size(m)
}
func (m *EmojizeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmojizeReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmojizeReply proto.InternalMessageInfo

func (m *EmojizeReply) GetEmojizedText() string {
	if m != nil {
		return m.EmojizedText
	}
	return ""
}

func init() {
	proto.RegisterType((*EmojizeRequest)(nil), "v1.EmojizeRequest")
	proto.RegisterType((*EmojizeReply)(nil), "v1.EmojizeReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmojiServiceClient is the client API for EmojiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmojiServiceClient interface {
	Emojize(ctx context.Context, in *EmojizeRequest, opts ...grpc.CallOption) (*EmojizeReply, error)
}

type emojiServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmojiServiceClient(cc *grpc.ClientConn) EmojiServiceClient {
	return &emojiServiceClient{cc}
}

func (c *emojiServiceClient) Emojize(ctx context.Context, in *EmojizeRequest, opts ...grpc.CallOption) (*EmojizeReply, error) {
	out := new(EmojizeReply)
	err := c.cc.Invoke(ctx, "/v1.EmojiService/Emojize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmojiServiceServer is the server API for EmojiService service.
type EmojiServiceServer interface {
	Emojize(context.Context, *EmojizeRequest) (*EmojizeReply, error)
}

func RegisterEmojiServiceServer(s *grpc.Server, srv EmojiServiceServer) {
	s.RegisterService(&_EmojiService_serviceDesc, srv)
}

func _EmojiService_Emojize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmojizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmojiServiceServer).Emojize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.EmojiService/Emojize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmojiServiceServer).Emojize(ctx, req.(*EmojizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmojiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.EmojiService",
	HandlerType: (*EmojiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emojize",
			Handler:    _EmojiService_Emojize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emoji.proto",
}

func init() { proto.RegisterFile("emoji.proto", fileDescriptor_emoji_f423687afb3d35a1) }

var fileDescriptor_emoji_f423687afb3d35a1 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcd, 0xcd, 0xcf,
	0xca, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x54, 0x52, 0xe1, 0xe2, 0x73,
	0x05, 0x09, 0x55, 0xa5, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0x94,
	0xa4, 0x56, 0x94, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0xc6, 0x5c, 0x3c,
	0x70, 0x55, 0x05, 0x39, 0x95, 0x42, 0xca, 0x5c, 0xbc, 0xa9, 0x10, 0x7e, 0x4a, 0x3c, 0x92, 0x62,
	0x1e, 0x98, 0x60, 0x48, 0x6a, 0x45, 0x89, 0x91, 0x3d, 0x54, 0x53, 0x70, 0x6a, 0x51, 0x59, 0x66,
	0x72, 0xaa, 0x90, 0x3e, 0x17, 0x3b, 0xd4, 0x10, 0x21, 0x21, 0xbd, 0x32, 0x43, 0x3d, 0x54, 0x7b,
	0xa5, 0x04, 0x50, 0xc4, 0x0a, 0x72, 0x2a, 0x93, 0xd8, 0xc0, 0xce, 0x34, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x4e, 0x77, 0x73, 0x11, 0xb5, 0x00, 0x00, 0x00,
}
